# UID TAGS
BUILDINGS_UID_TAG = "BLD"
ADDRESS_UID_TAG = "ADR"
EMPLOYEE_UID_TAG = "EMP"
BUILDING_EMPLOYEE_UID_TAG = "BUS"
MEMBERS_BRAND_UID_TAG = "BRA"
KITCHEN_UID_TAG = "KTC"
MEMBERS_BRAND_KITCHEN_UID_TAG = "MBK"
BUILDINGS_KITCHENS_UID_TAG = "BLK"
LOG_UID_TAG = "LOG"
BASKETS_UID_TAG = "BSK"
COURIER_OPERATION_UID_TAG = "COP"
COURIER_OPERATION_NONE_TAG = "N"
COURIERS_UID_TAG = "CUR"
MEMBERS_UID_TAG = "MEM"
RESTAURANTS_UID_TAG = "RST"
PM_Regions_of_OTM_Regions_UID_TAG = "ROT"
Restaurants_of_OTM_Regions_UID_TAG = "MOT"
OTM_COMMAND_HISTORY_UID_TAG = "OCH"
REGIONS_UID_TAG = "RGN"
OTM_REGIONS_UID_TAG = "OTM"
REGIONS_COMMAND_UID_TAG = "RGC"
PLATFORMS_PM_REGION_UID_TAG = "PPR"
BUILDINGS_AREA_UID_TAG = "BAR"
BUILDINGS_EMPLOYEES_UID_TAG = "BEM"
PM_KITCHENS_UID_TAG = "KIT"
OPTIONS_UID_TAG = "OPT"
PLATFORM_OPTIONS_UID_TAG = "POP"
PLATFORM_PRODUCTS_UID_TAG = "PPR"


# OTM DATA
OTM_MIN_BASKET_PRICE_MIN_VALUE = 1
OTM_MIN_DELIVER_TIME_MIN_VALUE = 20
OTM_MIN_DELIVER_TIME_MAX_VALUE = 55
OTM_MAX_DELIVER_TIME_MIN_VALUE = 30
OTM_MAX_DELIVER_TIME_MAX_VALUE = 65
OTM_DELIVER_TIME_MULTIPLE_OF = 5

COMMAND_TYPE_CREATE = "Oluşturma"
COMMAND_TYPE_DELETE = "Silme"
COMMAND_TYPE_UPDATE = "Düzenleme"
COMMAND_TYPE_ACTIVATE = "Uygulanma"
COMMAND_TYPE_FAIL = "Başarısız"


# Status
STATUS_PREPARING = "PREPARING"
STATUS_PREPARED = "PREPARED"
STATUS_ONTHEWAY = "ONTHEWAY"
STATUS_PENDING = "PENDING"
STATUS_ONTHEWAY_TO_BASE = "ONTHEWAY_TO_BASE"
STATUS_READY_TO_ONTHEWAY = "READY_TO_ONTHEWAY"
STATUS_ASSIGNED_TO_COURIER = "ASSIGNED_TO_COURIER"
STATUS_ASSIGNED_BASKET = "ASSIGNED_BASKET"
STATUS_COMPLETED = "COMPLETED"
STATUS_BASKET_PENDING = "PENDING"
STATUS_BASKET_ASSIGNED_TO_COURIER = "ASSIGNED_TO_COURIER"
STATUS_BASKET_READY_TO_ONTHEWAY = "READY_TO_ONTHEWAY"
STATUS_BASKET_ONTHEWAY = "ONTHEWAY"
STATUS_BASKET_COMPLETED = "COMPLETED"
BILLING_STATUS_ZOMBIE = "ZOMBIE"
BILLING_STATUS_COMPLETED = "COMPLETED"
BILLING_STATUS_PENDING = "PENDING"
BILLING_STATUS_CANCELLED = "CANCELLED"
STATUS_ROBOT = "ROBOT"
STATUS_SCHEDULED = "SCHEDULED"
STATUS_CANCELLED = "CANCELLED"
STATUS_DELIVERED = "DELIVERED"
STATUS_NOTDELIVERED = "NOTDELIVERED"


MANAGER_TYPE = "MANAGER"
EMPLOYEE_TYPE = "EMPLOYEE"

PM_BUILDINGS_TABLE_NAME = ""


THRESHOLD_DISTANCE_VALUE = 200

class CancelledBillsContants:
    EXCEL_NAME = "İptal_Adisyonlar"
    PDF_NAME = "İptal_Adisyonlar"
    BRAND = "Şube"
    ORDER_NO = "Sipariş No"
    BRAND_SHIPPING_COSTS = "Üye'den G.Ü Alınacak mi"
    COURIER_BONUS = "Kuryeye Prim Verilecek mi"
    DESCRIPTION = "Açıklama"
    YES = "Evet"
    NO = "Hayır"

SEARCH_LIMIT_RECORD = 5
TOLERANCE_PAYMENT = 0.50
PAYMENT_PER_BASKET = 3.0


DELIVERY_METHOD_PM_COURIER = "1"
DELIVERY_METHOD_PLATFORM_COURIER = "2"
DELIVERY_METHOD_HAND_DELIVERY = "3"
DELIVERY_METHOD_RESTAURANT_COURIER = "4"

DELIVERY_METHOD_PM_COURIER_TEXT = "Paket Mutfak Kuryesi"
DELIVERY_METHOD_PLATFORM_COURIER_TEXT = "Platform Kuryesi"
DELIVERY_METHOD_HAND_DELIVERY_TEXT = "Kuryesiz teslimat"
DELIVERY_METHOD_RESTAURANT_COURIER_TEXT = "Restoran Kuryesi"

DELIVERY_METHOD_HAND_DELIVERY_TO_PM_EMPLOYEES = "5"

ORDER_TYPE_PLATFORM = "1"
ORDER_TYPE_MANUEL_ORDER_WITH_PHONE = "2"
ORDER_TYPE_MANUEL_ORDER = "3"
ORDER_WITH_PHONE_TEXT = "Telefon ile sipariş"
MANUEL_ORDER_TEXT = "Manuel sipariş"

FAKE_ORDER = "1"
REAL_ORDER = "0"

PAYMENT_LOCATION_ONLINE = "ONLINE"

NO_RESTAURANT_TRANSFER_PAYMENT = "0"

BRANDS_LOG_LIMIT = 5

PAREKENDE_SATIS_FISI_LIMIT = 2000.0

# TABLE NAMES ########################
ORDERS_ARCHIVE_TABLE_NAME = "Orders_Archive"
MEMBERS_BRANDS_TABLE_NAME = "Members_Brands"
MEMBERS_TABLE_NAME = "Members"
COURIERS_TABLE_NAME = "Couriers"
PM_USERS_TABLE_NAME = "Pm_Users"
PAYMENT_METHODS_TABLE_NAME = "Payment_Methods"
# TABLE NAMES ########################

# DB FIELD NAMES ######################
FIELD_PLATFORM_NAME = "platform_name"
FIELD_DELIVERY_METHOD = "delivery_method"
FIELD_BILLING_STATUS = "billing_status"
FIELD_PLATFORM_CODE = "platform_code"
FIELD_COURIER_PAYMENT = "has_courier_payment"
FIELD_HAS_RESTAURANT_TRANSFER_PAYMENT = "has_restaurant_transfer_payment"
# DB FIELD NAMES ######################


COURIER_DASHBOARD_URL = ""




DELIVERY_METHOD_PM_COURIER = "1"



STATUS_END_OF_DAY_PENDING = 'PENDING'
STATUS_END_OF_DAY_STARTED = 'THE_DAY_STARTED'
STATUS_END_OF_DAY_OVER = 'THE_DAY_OVER'

YEMEK_SEPETI_NO = "1"
GETIR_NO = "2"
TRENDYOL_NO = "3"

PLATFORM_NAME_YS = "Yemeksepeti"
PLATFORM_NAME_TY = "Trendyol"
PLATFORM_NAME_GT = "Getir"
PLATFORM_NAME_PHONE = "Telefon ile Sipariş"
PLATFORM_NAME_HAND_DELIVERY = "Gel Al Siparişi"
PLATFORM_NAME_PM_EMPLOYEE = "Paket Mutfak Çalışan Siparişi"
PLATFORM_NAME_ADDITIONAL = "Ek Sipariş"


BRANDS_PLATFORM_STATUS_CLOSE = "Close"
BRANDS_PLATFORM_STATUS_OPEN = "Open"

GETIR_STATUS_OPEN_CLOSE_RATELIMITER = 30 # 30 saniye'de bir bu istek kullanılabilir.
GETIR_UPDATE_STATUS_RATE_LIMITER = 60 # 60 saniye'de bir bu istek kullanılabilir.

DELIVERY_METHOD_PM_COURIER = "1"
DELIVERY_METHOD_PLATFORM_COURIER = "2"
DELIVERY_METHOD_HAND_DELIVERY = "3"
DELIVERY_METHOD_RESTAURANT_COURIER = "4"
DELIVERY_METHOD_HAND_DELIVERY_TO_PM_EMPLOYEES = "5"


PLATFORMS_NAMES_OBJECT = {
    PLATFORM_NAME_YS: YEMEK_SEPETI_NO,
    PLATFORM_NAME_GT: GETIR_NO,
    PLATFORM_NAME_TY: TRENDYOL_NO
}


KITCHEN_EMPLOYEE_ROLE_TYPE = "KITCHEN_EMPLOYEE"






PLATFORM_GT_NAME = "Getir"
PLATFORM_YS_NAME = "Yemeksepeti"
PLATFORM_TY_NAME = "Trendyol"

ORDER_STATUS_CANCELLED = "Cancelled"
ORDER_STATUS_ONDELIVERY = "OnDelivery"
ORDER_STATUS_PREPARE = "Prepare"
ORDER_STATUS_DELIVERED = "Delivered"

SKYE_SUITE_URL = ""
PMC_APP_URL = ""

COURIER_ROLE_ID = '14'
PASSIVE_WORKING_STATUS = 0
ACTIVE_WORKING_STATUS = 1
PENDING_WORKING_STATUS = 2


TURKEY_ADDRESSES = "Turkey_Addresses"
PM_BUILDINGS_TABLE_NAME = ""



MAX_ORDER_COUNT_IN_BASKET = 10



STATUS_PREPARING_ID = "3"
STATUS_ONTHEWAY_TO_DELIVER = "ONTHEWAY_TO_DELIVER"
STATUS_COMPLETED_ID = "4"
BASKET_STATUS_RAFTA_ID = "2"
BASKET_STATUS_ON_THE_WAY_ID = "5"

PLATFORM_STATUS_ON_DELIVERY = "OnDelivery"
PLATFORM_STATUS_DELIVERED = "Delivered"





GETIR_UPDATE_STATUS_RATE_LIMITER = 90
# 60 saniye'de bir bu istek kullanılabilir. + 30 saniye pay



TRENDYOL_REGION_STATUS_AVAILABLE = "AVAILABLE"
TRENDYOL_REGION_STATUS_UNAVAILABLE = "UNAVAILABLE"


API_CONFIG_CRITICAL_ERROR = 87

OK = 0
REQUEST_ERROR = -1
EXCEPTION_ERROR = -2


request_error_format = {"status": "", "description": "", "platform": ""}

test_kitchen_id = "KTC-1643120008-RNKZSGQOFP-0000544097"
test_pm_restaurant_id = "RST-1643793258-DZLQL4W36R-0000702417"
test_kitchen_no = "1"
test_building_id = "BLD-1636968717-5D9KDF4LO4-0005273106"
test_building_name = "Şerifali PM"

test_brand_id = "BRA-1643793141-VN5E8B2HLG-0000544041"
test_brand_name = "Şerifali Pidecisi"

test_member_id = "BRA-1643793141-VN5E8B2HLG-0000544041"
test_member_name = "Şerifali Pidecisi"


MAX_CONFIG_ATTEMPT_COUNT = 10
MAX_METADATA_ATTEMPT_COUNT = 10

PLATFORM_NAME_MANUEL_ORDER = "Manuel Sipariş"
PLATFORM_NAME_MANUEL_ORDER_WITH_PHONE = "Telefon ile Sipariş"
PLATFORM_NAME_PM_EMPLOYEE_ORDER = "Paket Mutfak Çalışan Siparişi"
PLATFORM_NAME_ADDITIONAL_ORDER = "Ek Sipariş"
PLATFORM_NAME_HAND_DELIVERY = "Gel Al Siparişi"

GETIR_SCHEDULED_BEFORE_ORDER_HOUR = 58
# Teslimat saatinden 1 saat önce sipariş hazırlanıyor oluyor. 1 saat yerine garanti olsun diye 58 dakika koyulmuştur






PLATFORM_GT_NAME = "Getir"
PLATFORM_YS_NAME = "Yemeksepeti"
PLATFORM_TY_NAME = "Trendyol"


YS_PLATFORM_ID = 1
GT_PLATFORM_ID = 2
TY_PLATFORM_ID = 3
MANUEL_ORDER_ID = 4

ORDER_STATUS_CANCELLED = "Cancelled"
ORDER_STATUS_ONDELIVERY = "OnDelivery"
ORDER_STATUS_PREPARE = "Prepare"
ORDER_STATUS_DELIVERED = "Delivered"

GT_ORDER_STATUS_CANCELLED_URL = "cancel"
GT_ORDER_STATUS_PREPARE_URL = "prepare"
GT_ORDER_STATUS_DELIVERED_URL = "deliver"


DELIVERY_METHOD_PM_COURIER_TEXT = "PM_COURIER"
DELIVERY_METHOD_PLATFORM_COURIER_TEXT = "PLATFORM_COURIER"
DELIVERY_METHOD_HAND_DELIVERY_TEXT = "HAND_DELIVERY"
DELIVERY_METHOD_RESTAURANT_COURIER_TEXT = "RESTAURANT_COURIER"

CUSTOMER_TYPE_PM_EMPLOYEE = "1"
CUSTOMER_TYPE_PLATFORM_CUSTOMER = "2"
CUSTOMER_TYPE_CUSTOMER = "3"

CUSTOMER_TYPE_PM_EMPLOYEE_TEXT = "PM-EMPLOYEE"
CUSTOMER_TYPE_PLATFORM_CUSTOMER_TEXT = "PLATFORM-CUSTOMER"
CUSTOMER_TYPE_CUSTOMER_TEXT = "CUSTOMER"

ORDER_TYPE_PLATFORM = "1"
ORDER_TYPE_MANUEL_ORDER_WITH_PHONE = "2"
ORDER_TYPE_MANUEL_ORDER = "3"

ORDER_TYPE_PLATFORM_TEXT = "PLATFORM"
ORDER_TYPE_MANUEL_ORDER_WITH_PHONE_TEXT = "MANUEL_ORDER_WITH_PHONE"
ORDER_TYPE_MANUEL_ORDER_TEXT = "MANUEL_ORDER"
ORDER_TYPE_ADDITIONAL_TEXT = "ADDITIONAL_ORDER"
ORDER_TYPE_HAND_DELIVERY_TEXT = "HAND_DELIVERY_ORDER"
ORDER_TYPE_EMPLOYEE_TEXT = "EMPLOYEE_ORDER"

PAYMENT_LOCATION_ONLINE = "1"
PAYMENT_LOCATION_AT_THE_DOOR = "2"
PAYMENT_LOCATION_AT_RESTAURANT = "3"

PAYMENT_LOCATION_ONLINE_TEXT = "ONLINE"
PAYMENT_LOCATION_AT_THE_DOOR_TEXT = "AT_THE_DOOR"
PAYMENT_LOCATION_AT_RESTAURANT_TEXT = "AT_RESTAURANT"

FAKE_ORDER = "1"
NO_FAKE_ORDER = "0"

UNEXPECTED_ERROR_ON_SERVICE_MESSAGE: int = 1
MISSING_DATA_ERROR_MESSAGE = 3
BUILDING_NOT_FOUND_ERROR_MESSAGE = 5
BRAND_NOT_FOUND_ERROR_MESSAGE = 6
DATA_FORMAT_ERROR_MESSAGE = 7
MISSING_TOKEN_ERROR_MESSAGE = 11

YS_PLATFORM_NAME = "Yemeksepeti"
TY_PLATFORM_NAME = "Trendyol"
GT_PLATFORM_NAME = "Getir"


COURIER_ROLE_NAME = "COURIER"

KITCHEN_EMPLOYEE_ROLE_TYPE = "KITCHEN_EMPLOYEE"
THRESHOLD_TIME_OTP = 90


COURIER_ROLE_ID = 14


REGIONS_COMMANDS_DB_NAME = "Regions_Commands"
OTM_REGIONS_DB_NAME = "OTM_Regions"
REGIONS_DB_NAME = "PM_Regions"
TR_ADDRESSES_DB_NAME = "Turkey_Addresses"
BUILDING_ADDRESSES_DB_NAME = "Buildings_Adresses"
PLATFORMS_PM_REGION_DB_NAME = "Platform_Pm_Regions"
GETIR_NAME = "GTR"
YEMEK_SEPETI_NAME = "YS"
TRENDYOL_NAME = "TY"

BUILDING_PM_REGIONS_STATUS_NOT_INTEGRATED = "NOT_INTEGRATED"
BUILDING_PM_REGIONS_STATUS_NOT_CREATED = "NOT_CREATED"
BUILDING_PM_REGIONS_STATUS_CREATED = "CREATED"
BUILDING_PM_REGIONS_STATUS_COMPLETED = "COMPLETED"



PLATFORM_NAME_TRENDYOL = "Trendyol"
PLATFORM_NAME_YEMEKSEPETI = "Yemeksepeti"
PLATFORM_NAME_GETIR = "Getir"
BUILDINGS_AREA_DB_NAME = "PM_Buildings_Areas"



YS_PLATFORM_NO = "1"
GT_PLATFORM_NO = "2"
TY_PLATFORM_NO = "3"

PRODUCT_CODE = 10000

PAYMENT_LOCATION_ONLINE = "ONLINE"
PAYMENT_LOCATION_AT_THE_DOOR = "AT_THE_DOOR"
PAYMENT_LOCATION_AT_THE_RESTAURANT = "AT_THE_RESTAURANT"


# ORDER TYPES
ORDER_TYPE_PLATFORM = "PLATFORM"
ORDER_TYPE_WITH_PHONE = "MANUEL_ORDER_WITH_PHONE"
ORDER_TYPE_MANUEL_ORDER = "MANUEL_ORDER"
ORDER_TYPE_ADDITIONAL = "ADDITIONAL_ORDER"
ORDER_TYPE_HAND_DELIVERY = "HAND_DELIVERY_ORDER"
ORDER_TYPE_EMPLOYEE = "EMPLOYEE_ORDER"


TYPE_NOT_CREATED = "NOTCREATED"
TYPE_CREATED = "CREATED"

DB_NAME_PM_BUILDINGS = "PM_Buildings"
DB_NAME_COURIERS = "Couriers"
DB_NAME_PM_USERS = "Pm_Users"
DB_NAME_ERROR_MESSAGES = "Error_Messages"



service_error = "SERV-ERR"


ON_THE_WAY = "ON_THE_WAY"
ON_THE_BASE = "ON_THE_BASE"
AVAILABLE = "AVAILABLE"
ON_THE_WAY_TO_BASE = "ON_THE_WAY_TO_BASE"

COURIERS_STATUS_PENDING = "PENDING"
COURIERS_STATUS_ASSIGNED_BASKET = "ASSIGNED_BASKET"
COURIERS_STATUS_READY_TO_ONTHEWAY = "READY_TO_ONTHEWAY"
COURIERS_STATUS_ONTHEWAY_TO_DELIVER = "ONTHEWAY_TO_DELIVER"
COURIERS_STATUS_ONTHEWAY_TO_BASE = "ONTHEWAY_TO_BASE"
COURIERS_STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"
MORE_ASSINGED_BASKET_ERROR = "MORE_ASSINGED_BASKET"
HAS_ACTIVE_BASKET = "HAS_ACTIVE_BASKET"


COURIER_CONTRACT_TYPE_PART_TIME = "Part Time"
COURIER_CONTRACT_TYPE_FULL_TIME = "Full Time"

COURIER_TYPE_FORMER = "FORMER"
COURIER_TYPE_UNVERIFIED = "UNVERIFIED"
COURIER_TYPE_ACTIVE = "ACTIVE"


# COURIER OPS TAGS

# COURIER OPS TAGS
COURIER_OPERATION_TXN_CODE_GPS = "CUR_GPS"
COURIER_OPERATION_TXN_CODE_CREATE_BASKET_AND_ASSING = "CUR_CREATE_BASKET_AND_ASSING"
COURIER_OPERATION_TXN_CODE_NOT_AVAILABLE = "CUR_NOT_AVAILABEL"
COURIER_OPERATION_TXN_CODE_RETURN_BUILDING = "CUR_RETURN_BUILDING"
COURIER_OPERATION_TXN_CODE_BASKET_ONTHEWAY = "CUR_BASKET_ONTHEWAY"
COURIER_OPERATION_TXN_CODE_BASKET_CLEAR = "CUR_BASKET_CLEAR"
COURIER_OPERATION_TXN_CODE_ON_BUILDING = "CUR_ON_BUILDING"
COURIER_OPERATION_TXN_CODE_BASKET_FINISHED = "CUR_BASKET_FINISHED"
COURIER_OPERATION_TXN_CODE_ORDER_ONTHEWAY = "CUR_ORDER_ONTHEWAY"
COURIER_OPERATION_TXN_CODE_ORDER_DELIVERED = "CUR_ORDER_DELIVERED"
COURIER_OPERATION_TXN_CODE_ORDER_NOT_DELIVERED = "CUR_ORDER_NOT_DELIVERED"

PLATFORM_ID_YS = "1"
PLATFORM_ID_GT = "2"
PLATFORM_ID_TY = "3"

GETIR_UPDATE_STATUS_RATE_LIMITER = 60 + 30